export type PlaybookType = "forward"
export type PlaybookStatus = "draft" | "running" | "completed"
export type StopLossType = "fixed" | "atr" | "percent"
export type TakeProfitType = "fixed" | "rr-ratio" | "percent"
export type PositionSizingType = "fixed" | "percent-equity"